### ISSUE TITLE
[Production] Skills checkboxes not rendering for freelancer registration form

### ISSUE THREAD

**Issue by TyJacalan** [TyJacalan/booking-app#114]
## Demo
<img width="475" alt="Screenshot 2024-06-07 at 2 39 48 PM" src="https://github.com/TyJacalan/booking-app/assets/143598524/f066c979-820d-4bb4-81e2-61cf6a239b03">

Html:
<img width="1002" alt="Screenshot 2024-06-07 at 3 39 10 PM" src="https://github.com/TyJacalan/booking-app/assets/143598524/4c652149-9ab1-4bf3-af44-8052121c8263">

**Comment by cimafrancamae** [comment]
@TyJacalan PR #111 covers this issue

**Comment by cimafrancamae** [comment]
> @TyJacalan PR #111 covers this issue

The categories are assigned in the seed, and the skills are taken from the categories. Does that causes an issue in production?

**Comment by TyJacalan** [comment]
ah yeah, will probably have to do the same thing as #108 where freelancer and client roles were created on app initialization

**Comment by cimafrancamae** [comment]
> ah yeah, will probably have to do the same thing as #108 where freelancer and client roles were created on app initialization.
> 
> I'm not sure if PR: #111 fixes the issue since the seed file isn't being run on production.

Oh! okay, will do a migration for this

**Comment by cimafrancamae** [comment]
The migration is on PR #115  @TyJacalan
