### ISSUE TITLE
Dates less than current date should be blocked automatically

### ISSUE THREAD

**Issue by cimafrancamae** [TyJacalan/booking-app#130]

**Comment by p3rc1us** [comment]
Somewhat this might be a fix, but there are pundit errors. @TyJacalan @cimafrancamae 

```
def index
   ...
  @blocked_dates = current_user.blocked_dates + past_blocked_dates
   ...
end

private

def past_blocked_dates
    (Date.today.beginning_of_year..Date.yesterday).map do |date|
      BlockedDate.new(date:, user: current_user)
    end
  end
 ```

**Comment by cimafrancamae** [comment]
What are the pundit errors? To authorize an action, you can put something like `authorize Appointment` for the model or `authorize @appointment` for specific values or `authorize Appointment, :show?`  for controller action @p3rc1us

**Comment by TyJacalan** [comment]
There's no need for this. Past dates are already blocked from the appointment_controller (config for flatpickr). 

This just populates the database by adding multiple dates for the year. Every freelancer will end up having hundreds of dates in the BlockedDates model.
