### ISSUE TITLE
[In Production] OnRender redirection after payment

### ISSUE THREAD

**Issue by p3rc1us** [TyJacalan/booking-app#135]
- made an appointment in development but get redirected after in production XD

![image](https://github.com/TyJacalan/booking-app/assets/144686514/003d987e-5072-4714-9409-c394e1f068d7)

**Comment by TyJacalan** [comment]
The return url in the [payment_intents.rb](app/services/paymongo/payment_intents.rb) points to the `HOST_URL` from the credentials. 
```
        return_url: "#{Rails.application.credentials.HOST_URL}/appointments"
```
In you local machine, it's probably set to the production host url. All you have to do is edit your credentials and set it to the local host (but don't push any credential changes).
