### ISSUE TITLE
Accessing appointment routes as guest throws errors

### ISSUE THREAD

**Issue by TyJacalan** [TyJacalan/booking-app#28]
## Issue

This issue is related to PR(#23) when `before_action :authenticate_user!` was removed from the _AppointmentsController_

Accessing any of the appointments routes throws errors because to build the resources: `@appointments` or `@appointment`, user related parameters are required. Example:
```
def index
   @appointments = Appointment.where(client_id: current_user.id)
                                ...
                                ...
   authorize @appointments
```

- The first line will throw an error for guest users because `current_user` does not exist.
- Pundit is not able to intercept because it only gets triggered after the error occurs

## Solution

We should still authenticate the user for the appointments controller as only logged in users can access these routes. The only issue is that it will redirect guests to the signin page and that may not be the intended response. Is there a way to trigger Pundit before the error is thrown?

**Comment by cimafrancamae** [comment]
<img width="960" alt="image" src="https://github.com/TyJacalan/booking-app/assets/65450522/8cc7565d-0041-4ccf-86c2-0c4d04eaec9e">

For guest users, I disabled the create appointment button

Reference: commit 6a88f149035d3665212eed27c98d987d94d05c12
