### ISSUE TITLE
Migration gets interrupted when running seed file to generate services

### ISSUE THREAD

**Issue by TyJacalan** [TyJacalan/booking-app#42]
## Issue
Running `bin/rails db:reset` or `bin/rails db:seed` gets interrupted when generating services. The interruption is likely caused by PR: #35, where the `:categories` attribute is still being populated when generating _Services_

## Possible Solution
1. Create a seed file for categories.
2. Ensure that the seeding for categories runs before services.
3. Reference the categories when generating services

Note: see relationship between [service](https://github.com/TyJacalan/booking-app/blob/main/db/seeds/services.rb) and [reviews](https://github.com/TyJacalan/booking-app/blob/main/db/seeds/reviews.rb) for reference.

**Comment by cimafrancamae** [comment]
There's already a category seed from PR #40
`db/seeds.rb` and `db/seeds/services.rb` have been updated
and has been merged to dev as well
@TyJacalan @p3rc1us
