### ISSUE TITLE
Production Issue from Gemfile related to pundit matchers gem

### ISSUE THREAD

**Issue by TyJacalan** [TyJacalan/booking-app#46]
Issue from the render build

I'm not sure where this came from @cimafrancamae @p3rc1us 

![2024-05-29-213457_805x224_scrot](https://github.com/TyJacalan/booking-app/assets/143598524/55a0efb8-fbab-4e41-8ca0-168c6a1e451c)

**Comment by cimafrancamae** [comment]
I added `pundit-matchers` back to the gemfile. Not sure how it disappeared. It's just for `rspec`. 
I pushed it directly to dev. Will you try building it again? @TyJacalan

**Comment by p3rc1us** [comment]
when I pull feat/paymongo and run `bundle`

![image](https://github.com/TyJacalan/booking-app/assets/144686514/3f574bd6-0dfd-49d3-9c24-d846bbeb3533)

**Comment by TyJacalan** [comment]
works now, thanks @cimafrancamae and @p3rc1us !
