### ISSUE TITLE
Refactor duplicate files

### ISSUE THREAD

**Issue by TyJacalan** [TyJacalan/booking-app#55]
We should conditionally render components from one file instead of loading entirely different files based on certain conditions (i.e. if the user is signed in or not). Unless there are significant layout changes, having two separate files may causes issues with consistency (i.e. account modal from the root_path is not the same as account modal from appointments path), and presents a problematic developer experience of having to modify two files when updating a component that appears in both files.

It only makes sense if the layouts between the two files are significantly different ([new service](https://github.com/TyJacalan/booking-app/blob/main/app/views/layouts/new_service.html.erb) layout is a decent example of this use case), in that case, we can create partials for shared components (i.e. account modal, mode switch, alerts) and render them between the two files. But, in this case, the container styles are the same.

1. Refactor duplicate layout files ([user](https://github.com/TyJacalan/booking-app/blob/main/app/views/layouts/user.html.erb), [application](https://github.com/TyJacalan/booking-app/blob/main/app/views/layouts/application.html.erb))

**If the only change is the header we can conditionally render it instead.**
```
<% if current_user %>
   <title>Signed in</title>
<% else %>
   <title>Not signed in</title>
<% end %>
```
**Removing the user layout also removes the need to set the layout in the controllers**
```
  # appointments controller
  layout 'user', only: [:index]

  # users controller
  layout :set_layout
```

2. Refactor duplicate navbar files ([user nav,](https://github.com/TyJacalan/booking-app/blob/main/app/views/layouts/_user_nav.html.erb) [nav](https://github.com/TyJacalan/booking-app/blob/main/app/views/layouts/_navbar.html.erb))

**Wrap the nav links in a controller condition**
```
<% if current_user && params[:controller] == 'services' && params[:action] == 'index' %>
   <%# nav links %>
<% end %>
```
##
This is a just a proposal, let me know your thoughts on this. @cimafrancamae

**Comment by cimafrancamae** [comment]
Totally agree! I initially thought the user navigations would be a lot different, but turns out it's not. Thanks for calling this out! Fixed it at PR #57 @TyJacalan
