### ISSUE TITLE
Error when deleting account

### ISSUE THREAD

**Issue by TyJacalan** [TyJacalan/booking-app#99]
## Issue

1. No user foreign key (should be freelancer and client) in Appointments and Review model.
2. No user reference in Category model. Can you confirm that the `has_many` categories is not being used by the User? @p3rc1us

**Comment by p3rc1us** [comment]
yep, User is not using has_many categories. 
Reference `20240528073830_remove_user_id_from_categories.rb` @cimafrancamae
